carp-team-llc/izy-tasks-server

- package.json
- prisma/schema.prisma
- src/controllers/auth/Login.ts
- src/controllers/auth/UsersPanigation.ts
- src/controllers/tasks/dto/index.ts
- src/controllers/tasks/dto/tasks.dto.ts
- src/controllers/tasks/taskPanigation.ts
- src/modules/auth/auth.module.ts
- src/options/types/express.d.ts
- src/services/auth/auth.service.ts
- src/utils/middleware/authMiddleware.ts
- tsconfig.json
> update tasks panigation

- prisma/schema.prisma
- src/controllers/tasks/dto/tasks.dto.ts
- src/controllers/tasks/taskManager.ts
> Create delete task controller

- package-lock.json
- package.json
- prisma/schema.prisma
- src/constant/colors.ts
- src/constant/enumData.ts
- src/controllers/tasks/taskManager.ts
- src/controllers/tasks/taskStatusHandlers.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/taskStatusHandlers.service.ts
- src/services/tasks/tasks.service.ts
- yarn.lock
handle task status (cancel, completed, late, new, pending)
> handle task status (cancel, completed, late, new, pending)

- prisma/schema.prisma
- src/controllers/projects/ProjectManager.ts
- src/controllers/projects/dto/Project.dto.ts
- src/controllers/tasks/dto/tasks.dto.ts
- src/controllers/tasks/taskManager.ts
- src/controllers/tasks/taskPanigation.ts
- src/controllers/tasks/taskStatusHandlers.ts
- src/modules/initApi.ts
- src/modules/projects/project.module.ts
- src/services/projects/project.service.ts
- src/services/tasks/taskStatusHandlers.service.ts
- src/services/tasks/tasks.service.ts
add module project and create project manager controller
> add module project and create project manager controller

- prisma/schema.prisma
- src/controllers/projects/ProjectManager.ts
- src/controllers/projects/dto/Project.dto.ts
- src/modules/projects/project.module.ts
- src/services/projects/project.service.ts
> create project router

- prisma/schema.prisma
- src/constant/colors.ts
- src/constant/enumData.ts
- src/controllers/projects/ProjectManagement.ts
- src/controllers/projects/ProjectManager.ts
- src/modules/projects/project.module.ts
- src/services/projects/project.service.ts
create new EnumType and create project module
> create new EnumType and create project module

- package.json
- prisma/schema.prisma
- src/constant/enumData.ts
- src/controllers/projects/ProjectManager.ts
- src/controllers/tasks/TaskChart.ts
- src/controllers/tasks/dto/index.ts
- src/controllers/tasks/dto/tasks.dto.ts
- src/controllers/tasks/taskManager.ts
- src/controllers/teams/TeamManager.ts
- src/controllers/teams/dto/team.dto.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/chart.service.ts
- src/services/tasks/taskStatusHandlers.service.ts
- src/services/tasks/tasks.service.ts
- yarn.lock
> Update task module

- src/controllers/tasks/TaskChart.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/chart.service.ts
create api to response data for weekly chart
> create api to response data for weekly chart

- package.json
- src/controllers/tasks/TaskChart.ts
- src/controllers/tasks/taskPanigation.ts
- src/controllers/tasks/taskStatusHandlers.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/chart.service.ts
- yarn.lock
> build monthly chart module

- package.json
- src/controllers/auth/ForgotPassword.ts
- src/controllers/tasks/TaskNotifycation.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/notification.service.ts
- yarn.lock
create notification list api for dashboard
> create notification list api for dashboard

- src/controllers/tasks/TaskNotifycation.ts
change response of notification list api
> change response of notification list api

- src/controllers/teams/TeamManager.ts
- src/controllers/teams/dto/team.dto.ts
- src/modules/initApi.ts
- src/modules/teams/team.module.ts
- src/services/teams/team.service.ts
build team api and add team member
> build team api and add team member

- README.md
> api document

- package.json
- src/controllers/projects/ProjectManager.ts
- src/controllers/projects/dto/Project.dto.ts
> add project to team

- src/controllers/users/UserManager.ts
- src/controllers/users/dto/user.dto.ts
- src/modules/initApi.ts
- src/modules/users/user.module.ts
- src/services/users/user.service.ts
> build function create profile

- src/controllers/auth/Register.ts
- src/services/auth/auth.service.ts
- src/services/projects/project.service.ts
- src/services/tasks/chart.service.ts
- src/services/tasks/notification.service.ts
- src/services/tasks/taskStatusHandlers.service.ts
- src/services/tasks/tasks.service.ts
- src/services/teams/team.service.ts
> refactor code

- README.md
> Update Api Document

- prisma/schema.prisma
- src/controllers/projects/ProjectManager.ts
- src/controllers/projects/dto/Project.dto.ts
add role name, role code, role eng name and permission
> add role name, role code, role eng name and permission

- src/constant/colors.ts
- src/constant/enumData.ts
- src/controllers/setup/ProjectSetup.ts
- src/controllers/tasks/TaskChart.ts
- src/controllers/tasks/taskPanigation.ts
- src/controllers/tasks/taskStatusHandlers.ts
- src/modules/initApi.ts
- src/modules/setup/setup.module.ts
- src/modules/tasks/tasks.module.ts
- src/services/setup/setup.service.ts
- src/services/tasks/taskStatusHandlers.service.ts
- src/services/tasks/tasks.service.ts
- src/utils/middleware/permission/LoadUserInfo.ts
show status list, priority list, role list and update status doing for task
> Setup status, priority, role

- package.json
- prisma/schema.prisma
- src/controllers/sprints/SprintManager.ts
- src/controllers/sprints/sprint.dto.ts
- src/controllers/tasks/TaskChart.ts
- src/services/tasks/chart.service.ts
- src/utils/helper.ts
- yarn.lock
Update daily chart response data and add module sprint
> Update and add new module

- prisma/schema.prisma
- src/controllers/tasks/TaskNotifycation.ts
- src/controllers/tasks/dto/tasksList.dto.ts
- src/services/tasks/notification.service.ts
change model and write new api
> change model and write new api

- prisma/schema.prisma
- src/controllers/auth/Register.ts
- src/controllers/auth/dto/authInfo.dto.ts
- src/controllers/tasks/TaskList.ts
- src/controllers/tasks/TaskNotifycation.ts
- src/controllers/tasks/dto/tasksList.dto.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/notification.service.ts
- src/services/tasks/tasklist.service.ts
Create create task list function
> create module task list

- src/controllers/tasks/TaskList.ts
- src/modules/tasks/tasks.module.ts
- src/services/tasks/tasklist.service.ts
create task list pagination module
> create task list pagination module

- package-lock.json
- package.json
- prisma/schema.prisma
- src/constant/MailForm.ts
- src/controllers/auth/Login.ts
- src/controllers/auth/Register.ts
- src/controllers/mail/SendMail.ts
- src/controllers/tasks/dto/tasks.dto.ts
- src/controllers/tasks/taskManager.ts
- src/services/tasks/tasks.service.ts
- yarn.lock
> update create task and load notification

- .gitignore
- App.ts
- firebaseAdmin.ts
- firebaseConfig.ts
- package.json
- prisma/schema.prisma
- src/controllers/upload/upload.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/initApi.ts
- src/modules/upload/upload.module.ts
- src/options/types/type.d.ts
- src/services/upload/upload.service.ts
- src/utils/middleware/KeepFileMemory.ts
- src/utils/middleware/authentication/AccountMiddleware.ts
- src/utils/middleware/permission/LoadUserInfo.ts
- yarn.lock
> create module upload file

- App.ts
- src/controllers/projects/ProjectManagement.ts
- src/controllers/upload/upload.controller.ts
- src/modules/initApi.ts
- src/modules/projects/project.module.ts
- src/services/projects/project.service.ts
- src/services/upload/upload.service.ts
**module Upload**: _Fixed duplicate name bug, uploading photos with the same name multiple times will no longer cause an error_
**module Project**: _create add role method for admin in project_
> Fixed bug and create new method for project

- prisma/schema.prisma
- src/constant/enumData.ts
- src/controllers/tasks/TaskList.ts
- src/controllers/teams/TeamManager.ts
- src/modules/teams/team.module.ts
- src/services/teams/team.service.ts
update rule for member in team and fix bug cannot show task data in task list
> update rule for team and fix bug task list

- App.ts
- src/controllers/projects/ProjectInsights.ts
- src/modules/initApi.ts
- src/modules/projects/project.module.ts
- src/services/projects/projectInsight.service.ts
- src/utils/monitor/Project/TaskMonitor.ts
- src/utils/monitor/monitor.ts
update monitor syntax
update ProjectWorkload
> update project module
